export const emojisRuLocale = {
  //перевод текста внутри
  search: 'Поиск (на английском языке)',
  emojilist: 'Список смайлов',
  notfound: 'Смайлы не найдены',
  clear: 'Очистить',
  categories: {
    search: 'Результаты поиска',
    recent: 'Часто используемые',
    people: 'Улыбки и люди',
    nature: 'Животные и природа',
    foods: 'Еда и напитки',
    activity: 'Активности',
    places: 'Путешествия и места',
    objects: 'Объекты',
    symbols: 'Символы',
    flags: 'Флаги',
    custom: 'От Yummy',
  },
  skintones: {
    1: 'Стандартный тон кожи',
    2: 'Светлый тон кожи',
    3: 'Средне-светлый тон кожи',
    4: 'Средний тон кожи',
    5: 'Средне-темный тон кожи',
    6: 'Темный тон кожи',
  },
};

//кастомные смайлики
export const customEmojis = [
  {
    name: 'Chef Barbie',
    shortNames: ['chef'],
    text: '',
    emoticons: [],
    keywords: ['chef', 'barbie', 'girl'],
    imageUrl: 'assets/images/emojis/chef-barbie.png',
  },
  {
    name: 'Corgi Chef',
    shortNames: ['corgi-chef'],
    text: '',
    emoticons: [],
    keywords: ['chef', 'corgi', 'dog'],
    imageUrl: 'assets/images/emojis/corgi-chef.png',
  },
  {
    name: 'Rabbit Chef',
    shortNames: ['rabbit-chef'],
    text: '',
    emoticons: [],
    keywords: ['chef', 'rabbit'],
    imageUrl: 'assets/images/emojis/rabbit-chef.png',
  },
  {
    name: 'Mouse Chef',
    shortNames: ['mouse-chef'],
    text: '',
    emoticons: [],
    keywords: ['chef', 'mouse'],
    imageUrl: 'assets/images/emojis/mouse-chef.png',
  },
  {
    name: 'Little Chef',
    shortNames: ['little-chef'],
    text: '',
    emoticons: [],
    keywords: ['chef', 'little'],
    imageUrl: 'assets/images/emojis/little-chef.png',
  },
  {
    name: 'Hat Chef',
    shortNames: ['hat-chef'],
    keywords: ['chef', 'hat'],
    imageUrl: 'assets/images/emojis/chef-hat.png',
  },
  {
    name: 'Gummy Bear',
    shortNames: ['gummy-bear'],
    keywords: ['gummy', 'bear'],
    imageUrl: 'assets/images/emojis/gummy-bear.png',
  },
  {
    name: 'Chef Long',
    shortNames: ['chef-long'],
    keywords: ['chef', 'long'],
    imageUrl: 'assets/images/emojis/chef-long.png',
  },
  {
    name: 'Glasses Girl',
    shortNames: ['glasses-girl'],
    keywords: ['glasses', 'girl'],
    imageUrl: 'assets/images/emojis/glasses-girl.png',
  },
  {
    name: 'Victor Barinov',
    shortNames: ['victor-barinov'],
    keywords: ['victor', 'barinov'],
    imageUrl: 'assets/images/emojis/victor-barinov.png',
  },
  {
    name: 'Blue Gummy Bear',
    shortNames: ['blue-gummy-bear'],
    keywords: ['gummy', 'bear'],
    imageUrl: 'assets/images/emojis/blue-gummy-bear.png',
  },
  {
    name: 'Red Boy',
    shortNames: ['red-boy'],
    keywords: ['red', 'boy'],
    imageUrl: 'assets/images/emojis/red-boy.png',
  },
  {
    name: 'Chef Celebrating',
    shortNames: ['chef'],
    keywords: ['chef'],
    imageUrl: 'assets/images/emojis/chef-celebrating.png',
  },
  {
    name: 'Fat Chef',
    shortNames: ['fat-chef'],
    keywords: ['chef', 'fat'],
    imageUrl: 'assets/images/emojis/fat-chef.png',
  },
  {
    name: 'Green Eyed Girl',
    shortNames: ['green-girl'],
    keywords: ['green', 'eye'],
    imageUrl: 'assets/images/emojis/green-eyed-girl.png',
  },
  {
    name: 'Frog TV',
    shortNames: ['frog-tv'],
    keywords: ['frog', 'tv'],
    imageUrl: 'assets/images/emojis/frog-tv.png',
  },
  {
    name: 'alien-chef',
    shortNames: ['alienchef'],
    keywords: ['alien'],
    imageUrl: 'assets/images/emojis/alien-chef.png',
  },
  {
    name: 'bear-chef',
    shortNames: ['bearchef'],
    keywords: ['bear'],
    imageUrl: 'assets/images/emojis/bear-chef.png',
  },
  {
    name: 'bear-cake',
    shortNames: ['bearcake'],
    keywords: ['bear'],
    imageUrl: 'assets/images/emojis/bear-eating-a-cake.png',
  },
  {
    name: 'otter-cake',
    shortNames: ['ottercake'],
    keywords: ['otter'],
    imageUrl: 'assets/images/emojis/otter-cake.png',
  },
  {
    name: 'unicorn-cake',
    shortNames: ['unicorncake'],
    keywords: ['unicorn'],
    imageUrl: 'assets/images/emojis/unicorn-cake.png',
  },
  {
    name: 'cake-custom',
    shortNames: ['cake-custom'],
    keywords: ['cake'],
    imageUrl: 'assets/images/emojis/cake.png',
  },
  {
    name: 'pegasus',
    shortNames: ['pegasus'],
    keywords: ['pegasus'],
    imageUrl: 'assets/images/emojis/pegasus.png',
  },
  {
    name: 'pikachu',
    shortNames: ['pikachu'],
    keywords: ['pikachu'],
    imageUrl: 'assets/images/emojis/pikachu.png',
  },
  {
    name: 'pug',
    shortNames: ['pug'],
    keywords: ['pug'],
    imageUrl: 'assets/images/emojis/pug.png',
  },
  {
    name: 'potatoes',
    shortNames: ['potatoes'],
    keywords: ['potatoes'],
    imageUrl: 'assets/images/emojis/potatoes.png',
  },
  {
    name: 'robotchef',
    shortNames: ['robotchef'],
    keywords: ['robotchef'],
    imageUrl: 'assets/images/emojis/robot-chef.png',
  },
  {
    name: 'chef-toque',
    shortNames: ['chef-toque'],
    keywords: ['chef-toque'],
    imageUrl: 'assets/images/emojis/chef-toque.png',
  },
  {
    name: 'cooking-pan',
    shortNames: ['cooking-pan'],
    keywords: ['cooking-pan'],
    imageUrl: 'assets/images/emojis/cooking-pan.png',
  },
  {
    name: 'dog-cooking',
    shortNames: ['dog-cooking'],
    keywords: ['dog-cooking'],
    imageUrl: 'assets/images/emojis/dog-cooking.png',
  },
  {
    name: 'lil-chef',
    shortNames: ['lil-chef'],
    keywords: ['lil-chef'],
    imageUrl: 'assets/images/emojis/lil-chef.png',
  },
  {
    name: 'chef-foot',
    shortNames: ['chef-foot'],
    keywords: ['chef-foot'],
    imageUrl: 'assets/images/emojis/chef-foot.png',
  },
];
